export const C2S = {
  CREATE_ROOM: 'c2s:createRoom',
  JOIN_ROOM: 'c2s:joinRoom',
  LEAVE_ROOM: 'c2s:leaveRoom',
  RECONNECT: 'c2s:reconnect',
  UPDATE_SETTINGS: 'c2s:updateSettings',
  START_GAME: 'c2s:startGame',
  DEALING_READY: 'c2s:dealingReady',
  NIGHT_ACTION: 'c2s:nightAction',
  NIGHT_STEAL: 'c2s:nightSteal',
  NIGHT_READY: 'c2s:nightReady',
  ACCOMPLICE_SELECT: 'c2s:accompliceSelect',
  SEND_MESSAGE: 'c2s:sendMessage',
  CAST_VOTE: 'c2s:castVote',
  BACK_TO_LOBBY: 'c2s:backToLobby',
  REQUEST_VOICE_TOKEN: 'c2s:requestVoiceToken',
} as const;

export const S2C = {
  ERROR: 's2c:error',
  ROOM_STATE: 's2c:roomState',
  GAME_STATE: 's2c:gameState',
  PHASE_CHANGE: 's2c:phaseChange',
  NIGHT_PROGRESS: 's2c:nightProgress',
  NIGHT_YOUR_TURN: 's2c:nightYourTurn',
  NIGHT_ACTION_RESULT: 's2c:nightActionResult',
  DAY_NEW_MESSAGE: 's2c:dayNewMessage',
  VOTE_UPDATE: 's2c:voteUpdate',
  GAME_RESULT: 's2c:gameResult',
  PLAYER_JOINED: 's2c:playerJoined',
  PLAYER_LEFT: 's2c:playerLeft',
  PLAYER_DISCONNECTED: 's2c:playerDisconnected',
  PLAYER_RECONNECTED: 's2c:playerReconnected',
  VOICE_TOKEN: 's2c:voiceToken',
} as const;
